### ISSUE TITLE
YSUpload.com return "Error 404"

### ISSUE THREAD

**Issue by u2fly** [YSFHQ/migrator#1]
Snapshot
* http://web.archive.org/web/20170201130414/http://ysupload.com/

## Related discussion
https://forum.ysfhq.com/viewtopic.php?t=6501

**Comment by EricTendian** [comment]
Fixed by https://github.com/YSFHQ/migrator/commit/8b8cd9aec145c91fc796daaf98a37c169d69d85c or one of the commits in #2.
